-- MySQL Script generated by MySQL Workbench
-- mié 02 oct 2019 17:04:07 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alpha_world
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alpha_world
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alpha_world` DEFAULT CHARACTER SET utf8mb4 ;
USE `alpha_world` ;

-- -----------------------------------------------------
-- Table `alpha_world`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`accounts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `ip` VARCHAR(256) NOT NULL,
  `gmlevel` TINYINT(4) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`applied_updates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`applied_updates` (
  `id` VARCHAR(9) NOT NULL DEFAULT '000000000',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`areatrigger_teleport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`areatrigger_teleport` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Identifier',
  `name` TEXT NULL DEFAULT NULL,
  `required_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `required_item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `required_item2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `required_quest_done` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `target_map` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `target_position_x` FLOAT NOT NULL DEFAULT '0',
  `target_position_y` FLOAT NOT NULL DEFAULT '0',
  `target_position_z` FLOAT NOT NULL DEFAULT '0',
  `target_orientation` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`item_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`item_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `subclass` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `display_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `quality` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `buy_count` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `buy_price` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sell_price` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `inventory_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `allowable_class` MEDIUMINT(9) NOT NULL DEFAULT '-1',
  `allowable_race` MEDIUMINT(9) NOT NULL DEFAULT '-1',
  `item_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `required_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `required_skill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `required_skill_rank` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `required_spell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `required_honor_rank` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `required_city_rank` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `required_reputation_faction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `required_reputation_rank` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `max_count` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `stackable` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1',
  `container_slots` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_type1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value1` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value2` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value3` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value4` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value5` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type6` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value6` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type7` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value7` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type8` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value8` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type9` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value9` SMALLINT(6) NOT NULL DEFAULT '0',
  `stat_type10` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `stat_value10` SMALLINT(6) NOT NULL DEFAULT '0',
  `delay` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1000',
  `range_mod` FLOAT NOT NULL DEFAULT '0',
  `ammo_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `dmg_min1` FLOAT NOT NULL DEFAULT '0',
  `dmg_max1` FLOAT NOT NULL DEFAULT '0',
  `dmg_type1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `dmg_min2` FLOAT NOT NULL DEFAULT '0',
  `dmg_max2` FLOAT NOT NULL DEFAULT '0',
  `dmg_type2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `dmg_min3` FLOAT NOT NULL DEFAULT '0',
  `dmg_max3` FLOAT NOT NULL DEFAULT '0',
  `dmg_type3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `dmg_min4` FLOAT NOT NULL DEFAULT '0',
  `dmg_max4` FLOAT NOT NULL DEFAULT '0',
  `dmg_type4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `dmg_min5` FLOAT NOT NULL DEFAULT '0',
  `dmg_max5` FLOAT NOT NULL DEFAULT '0',
  `dmg_type5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `block` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `armor` SMALLINT(5) NOT NULL DEFAULT '0',
  `holy_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `fire_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `nature_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `frost_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `shadow_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `arcane_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `spellid_1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spelltrigger_1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spellcharges_1` TINYINT(4) NOT NULL DEFAULT '0',
  `spellppmrate_1` FLOAT NOT NULL DEFAULT '0',
  `spellcooldown_1` INT(11) NOT NULL DEFAULT '-1',
  `spellcategory_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spellcategorycooldown_1` INT(11) NOT NULL DEFAULT '-1',
  `spellid_2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spelltrigger_2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spellcharges_2` TINYINT(4) NOT NULL DEFAULT '0',
  `spellppmrate_2` FLOAT NOT NULL DEFAULT '0',
  `spellcooldown_2` INT(11) NOT NULL DEFAULT '-1',
  `spellcategory_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spellcategorycooldown_2` INT(11) NOT NULL DEFAULT '-1',
  `spellid_3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spelltrigger_3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spellcharges_3` TINYINT(4) NOT NULL DEFAULT '0',
  `spellppmrate_3` FLOAT NOT NULL DEFAULT '0',
  `spellcooldown_3` INT(11) NOT NULL DEFAULT '-1',
  `spellcategory_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spellcategorycooldown_3` INT(11) NOT NULL DEFAULT '-1',
  `spellid_4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spelltrigger_4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spellcharges_4` TINYINT(4) NOT NULL DEFAULT '0',
  `spellppmrate_4` FLOAT NOT NULL DEFAULT '0',
  `spellcooldown_4` INT(11) NOT NULL DEFAULT '-1',
  `spellcategory_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spellcategorycooldown_4` INT(11) NOT NULL DEFAULT '-1',
  `spellid_5` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spelltrigger_5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spellcharges_5` TINYINT(4) NOT NULL DEFAULT '0',
  `spellppmrate_5` FLOAT NOT NULL DEFAULT '0',
  `spellcooldown_5` INT(11) NOT NULL DEFAULT '-1',
  `spellcategory_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `spellcategorycooldown_5` INT(11) NOT NULL DEFAULT '-1',
  `bonding` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `page_text` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `page_language` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `page_material` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `start_quest` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `lock_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `material` TINYINT(4) NOT NULL DEFAULT '0',
  `sheath` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `random_property` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `set_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `max_durability` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `area_bound` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `map_bound` SMALLINT(6) NOT NULL DEFAULT '0',
  `duration` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `bag_family` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `disenchant_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `food_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `min_money_loot` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `max_money_loot` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `extra_flags` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`),
  INDEX `items_index` (`class` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`characters` (
  `guid` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Global Unique Identifier',
  `account` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Account Identifier',
  `name` VARCHAR(12) NOT NULL DEFAULT '',
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `gender` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `xp` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `money` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `skin` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `face` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `hairstyle` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `haircolour` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `facialhair` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `bankslots` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `talentpoints` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `skillpoints` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `position_x` FLOAT NOT NULL DEFAULT '0',
  `position_y` FLOAT NOT NULL DEFAULT '0',
  `position_z` FLOAT NOT NULL DEFAULT '0',
  `map` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Map Identifier',
  `orientation` FLOAT NOT NULL DEFAULT '0',
  `taximask` LONGTEXT NULL DEFAULT NULL,
  `online` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `totaltime` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `leveltime` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `extra_flags` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `zone` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `taxi_path` TEXT NULL DEFAULT NULL,
  `drunk` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `health` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power4` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `power5` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`),
  INDEX `idx_account` (`account` ASC),
  INDEX `idx_online` (`online` ASC),
  INDEX `idx_name` (`name` ASC),
  CONSTRAINT `char_acc`
    FOREIGN KEY (`account`)
    REFERENCES `alpha_world`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`character_inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`character_inventory` (
  `guid` INT(11) NOT NULL,
  `owner` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Global Unique Identifier',
  `player` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `bag` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `slot` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `item_template` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Item Identifier',
  `stackcount` INT(11) UNSIGNED NOT NULL DEFAULT '1',
  `SpellCharges1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `SpellCharges2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `SpellCharges3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `SpellCharges4` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `SpellCharges5` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`),
  INDEX `idx_guid` (`owner` ASC),
  INDEX `Player` (`player` ASC),
  INDEX `item_template_idx` (`item_template` ASC),
  CONSTRAINT `item_template`
    FOREIGN KEY (`item_template`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `player_guid`
    FOREIGN KEY (`player`)
    REFERENCES `alpha_world`.`characters` (`guid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`character_queststatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`character_queststatus` (
  `guid` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `quest` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `status` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `rewarded` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `explored` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
  `timer` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `mobcount1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `mobcount2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `mobcount3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `mobcount4` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `itemcount1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `itemcount2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `itemcount3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `itemcount4` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `reward_choice` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`, `quest`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`character_social`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`character_social` (
  `guid` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Character Global Unique Identifier',
  `friend` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Friend Global Unique Identifier',
  `ignore` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Friend Flags',
  PRIMARY KEY (`guid`, `friend`),
  INDEX `guid` (`guid` ASC),
  INDEX `friend` (`friend` ASC),
  CONSTRAINT `social_frn`
    FOREIGN KEY (`friend`)
    REFERENCES `alpha_world`.`characters` (`guid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `social_own`
    FOREIGN KEY (`guid`)
    REFERENCES `alpha_world`.`characters` (`guid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`creature_model_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`creature_model_info` (
  `modelid` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `bounding_radius` FLOAT NOT NULL DEFAULT '0',
  `combat_reach` FLOAT NOT NULL DEFAULT '0',
  `gender` TINYINT(3) UNSIGNED NOT NULL DEFAULT '2',
  `modelid_other_gender` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `modelid_other_team` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`modelid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`creatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`creatures` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `display_id1` MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
  `display_id2` MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
  `display_id3` MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
  `display_id4` MEDIUMINT(8) UNSIGNED NULL DEFAULT '0',
  `name` CHAR(100) NOT NULL DEFAULT '0',
  `subname` CHAR(100) NULL DEFAULT NULL,
  `gossip_menu_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `level_min` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `level_max` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `health_min` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `health_max` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `mana_min` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `mana_max` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `armor` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `faction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `npc_flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `speed_walk` FLOAT NOT NULL DEFAULT '1' COMMENT 'Result of 2.5/2.5, most common value',
  `speed_run` FLOAT NOT NULL DEFAULT '1.14286' COMMENT 'Result of 8.0/7.0, most common value',
  `scale` FLOAT NOT NULL DEFAULT '1',
  `detection_range` FLOAT NOT NULL DEFAULT '20',
  `call_for_help_range` FLOAT NOT NULL DEFAULT '5',
  `leash_range` FLOAT NOT NULL DEFAULT '0',
  `rank` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `xp_multiplier` FLOAT NOT NULL DEFAULT '1',
  `dmg_min` FLOAT NOT NULL DEFAULT '0',
  `dmg_max` FLOAT NOT NULL DEFAULT '0',
  `dmg_school` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
  `attack_power` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dmg_multiplier` FLOAT NOT NULL DEFAULT '1',
  `base_attack_time` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `ranged_attack_time` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `unit_class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `unit_flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `dynamic_flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `beast_family` TINYINT(4) NOT NULL DEFAULT '0',
  `trainer_type` TINYINT(4) NOT NULL DEFAULT '0',
  `trainer_spell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `trainer_class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `trainer_race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `ranged_dmg_min` FLOAT NOT NULL DEFAULT '0',
  `ranged_dmg_max` FLOAT NOT NULL DEFAULT '0',
  `ranged_attack_power` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `type_flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `loot_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `pickpocket_loot_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `skinning_loot_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `holy_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `fire_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `nature_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `frost_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `shadow_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `arcane_res` SMALLINT(5) NOT NULL DEFAULT '0',
  `spell_id1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spell_id2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spell_id3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spell_id4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spell_list_id` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `pet_spell_list_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `gold_min` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `gold_max` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ai_name` CHAR(64) NOT NULL DEFAULT '',
  `movement_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `inhabit_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3',
  `civilian` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `racial_leader` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `regeneration` TINYINT(3) UNSIGNED NOT NULL DEFAULT '3',
  `equipment_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `trainer_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `vendor_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `mechanic_immune_mask` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `school_immune_mask` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `flags_extra` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `script_name` CHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`entry`),
  INDEX `idx_name` (`name` ASC),
  INDEX `modelid_info_idx` (`display_id1` ASC),
  INDEX `model2_idx` (`display_id2` ASC),
  INDEX `model3_idx` (`display_id3` ASC),
  INDEX `model4_idx` (`display_id4` ASC),
  CONSTRAINT `model1`
    FOREIGN KEY (`display_id1`)
    REFERENCES `alpha_world`.`creature_model_info` (`modelid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `model2`
    FOREIGN KEY (`display_id2`)
    REFERENCES `alpha_world`.`creature_model_info` (`modelid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `model3`
    FOREIGN KEY (`display_id3`)
    REFERENCES `alpha_world`.`creature_model_info` (`modelid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `model4`
    FOREIGN KEY (`display_id4`)
    REFERENCES `alpha_world`.`creature_model_info` (`modelid`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`quests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`quests` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `Method` TINYINT(3) UNSIGNED NOT NULL DEFAULT '2',
  `ZoneOrSort` SMALLINT(6) NOT NULL DEFAULT '0',
  `MinLevel` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `MaxLevel` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `QuestLevel` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `Type` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RequiredClasses` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RequiredRaces` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RequiredSkill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RequiredSkillValue` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RepObjectiveFaction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RepObjectiveValue` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RequiredMinRepFaction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RequiredMinRepValue` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RequiredMaxRepFaction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RequiredMaxRepValue` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `SuggestedPlayers` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `LimitTime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `QuestFlags` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `SpecialFlags` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `PrevQuestId` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `NextQuestId` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `ExclusiveGroup` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `NextQuestInChain` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `SrcItemId` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `SrcItemCount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `SrcSpell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `Title` TEXT NULL DEFAULT NULL,
  `Details` TEXT NULL DEFAULT NULL,
  `Objectives` TEXT NULL DEFAULT NULL,
  `OfferRewardText` TEXT NULL DEFAULT NULL,
  `RequestItemsText` TEXT NULL DEFAULT NULL,
  `EndText` TEXT NULL DEFAULT NULL,
  `ObjectiveText1` TEXT NULL DEFAULT NULL,
  `ObjectiveText2` TEXT NULL DEFAULT NULL,
  `ObjectiveText3` TEXT NULL DEFAULT NULL,
  `ObjectiveText4` TEXT NULL DEFAULT NULL,
  `ReqItemId1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemId2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemId3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemId4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemCount1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemCount2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemCount3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqItemCount4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceId1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceId2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceId3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceId4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceCount1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceCount2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceCount3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSourceCount4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqCreatureOrGOId1` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `ReqCreatureOrGOId2` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `ReqCreatureOrGOId3` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `ReqCreatureOrGOId4` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `ReqCreatureOrGOCount1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqCreatureOrGOCount2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqCreatureOrGOCount3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqCreatureOrGOCount4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSpellCast1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSpellCast2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSpellCast3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ReqSpellCast4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemId1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemId2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemId3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemId4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemId5` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemId6` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemCount1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemCount2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemCount3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemCount4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemCount5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewChoiceItemCount6` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemId1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemId2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemId3` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemId4` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemCount1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemCount2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemCount3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewItemCount4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `RewRepFaction1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewRepFaction2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewRepFaction3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewRepFaction4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewRepFaction5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'faction id from Faction.dbc in this case',
  `RewRepValue1` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RewRepValue2` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RewRepValue3` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RewRepValue4` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RewRepValue5` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `RewOrReqMoney` INT(11) NOT NULL DEFAULT '0',
  `RewMoneyMaxLevel` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `RewSpell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewSpellCast` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `RewMailTemplateId` MEDIUMINT(8) NOT NULL DEFAULT '0',
  `RewMailDelaySecs` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `RewMailMoney` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `PointMapId` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `PointX` FLOAT NOT NULL DEFAULT '0',
  `PointY` FLOAT NOT NULL DEFAULT '0',
  `PointOpt` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmote1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmote2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmote3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmote4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmoteDelay1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmoteDelay2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmoteDelay3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `DetailsEmoteDelay4` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `IncompleteEmote` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `CompleteEmote` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmote1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmote2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmote3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmote4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay1` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay2` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay3` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `OfferRewardEmoteDelay4` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `StartScript` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `CompleteScript` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`creature_involvedrelation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`creature_involvedrelation` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Identifier',
  `quest` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Quest Identifier',
  PRIMARY KEY (`entry`, `quest`),
  INDEX `npc_involved_quest_idx` (`quest` ASC),
  CONSTRAINT `fk_creature_involvedrelation_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_creature_involvedrelation_2`
    FOREIGN KEY (`quest`)
    REFERENCES `alpha_world`.`quests` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`creature_loot_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`creature_loot_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'entry 0 used for player insignia loot',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `condition_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `npc_loot_item_idx` (`item` ASC),
  CONSTRAINT `fk_creature_loot_template_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_creature_loot_template_2`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`creature_questrelation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`creature_questrelation` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Identifier',
  `quest` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Quest Identifier',
  PRIMARY KEY (`entry`, `quest`),
  INDEX `npc_quest_relation_idx` (`quest` ASC),
  CONSTRAINT `fk_creature_questrelation_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_creature_questrelation_2`
    FOREIGN KEY (`quest`)
    REFERENCES `alpha_world`.`quests` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`gameobjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`gameobjects` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `type` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `displayId` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` VARCHAR(100) NOT NULL DEFAULT '',
  `castBarCaption` VARCHAR(100) NOT NULL DEFAULT '',
  `faction` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `flags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `size` FLOAT NOT NULL DEFAULT '1',
  `data1` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data2` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data3` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data4` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data5` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data6` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data7` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data8` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data9` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `data10` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `mingold` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `maxgold` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ScriptName` VARCHAR(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`entry`),
  INDEX `idx_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`gameobject_loot_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`gameobject_loot_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `condition_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `item_gobject_idx` (`item` ASC),
  CONSTRAINT `fk_gameobject_loot_template_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`gameobjects` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_gameobject_loot_template_2`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`item_loot_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`item_loot_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `condition_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `loot_item_idx` (`item` ASC),
  CONSTRAINT `fk_item_loot_template_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_item_loot_template_2`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`spawns_creatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`spawns_creatures` (
  `spawn_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Global Unique Identifier',
  `spawn_entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Creature Identifier',
  `spawn_map` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Map Identifier',
  `spawn_displayid` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spawn_equipmentid` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `spawn_positionX` FLOAT NOT NULL DEFAULT '0',
  `spawn_positionY` FLOAT NOT NULL DEFAULT '0',
  `spawn_positionZ` FLOAT NOT NULL DEFAULT '0',
  `spawn_orientation` FLOAT NOT NULL DEFAULT '0',
  `spawn_spawntime` INT(10) UNSIGNED NOT NULL DEFAULT '120',
  `spawn_spawndist` FLOAT NOT NULL DEFAULT '5',
  `spawn_currentwaypoint` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spawn_curhealth` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `spawn_curmana` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `spawn_deathstate` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spawn_movetype` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`spawn_id`),
  INDEX `idx_map` (`spawn_map` ASC),
  INDEX `idx_id` (`spawn_entry` ASC),
  INDEX `spawns_creatures_modelid` (`spawn_displayid` ASC),
  CONSTRAINT `spawn_entry`
    FOREIGN KEY (`spawn_entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `spawns_creatures_modelid`
    FOREIGN KEY (`spawn_displayid`)
    REFERENCES `alpha_world`.`creatures` (`display_id1`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 94503
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`npc_text`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`npc_text` (
  `id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `text0_0` LONGTEXT NOT NULL,
  `text0_1` LONGTEXT NOT NULL,
  `lang0` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob0` FLOAT NOT NULL DEFAULT '0',
  `em0_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em0_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em0_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em0_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em0_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em0_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text1_0` LONGTEXT NOT NULL,
  `text1_1` LONGTEXT NOT NULL,
  `lang1` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob1` FLOAT NOT NULL DEFAULT '0',
  `em1_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em1_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em1_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em1_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em1_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em1_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text2_0` LONGTEXT NOT NULL,
  `text2_1` LONGTEXT NOT NULL,
  `lang2` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob2` FLOAT NOT NULL DEFAULT '0',
  `em2_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em2_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em2_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em2_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em2_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em2_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text3_0` LONGTEXT NOT NULL,
  `text3_1` LONGTEXT NOT NULL,
  `lang3` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob3` FLOAT NOT NULL DEFAULT '0',
  `em3_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em3_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em3_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em3_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em3_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em3_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text4_0` LONGTEXT NOT NULL,
  `text4_1` LONGTEXT NOT NULL,
  `lang4` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob4` FLOAT NOT NULL DEFAULT '0',
  `em4_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em4_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em4_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em4_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em4_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em4_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text5_0` LONGTEXT NOT NULL,
  `text5_1` LONGTEXT NOT NULL,
  `lang5` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob5` FLOAT NOT NULL DEFAULT '0',
  `em5_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em5_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em5_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em5_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em5_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em5_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text6_0` LONGTEXT NOT NULL,
  `text6_1` LONGTEXT NOT NULL,
  `lang6` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob6` FLOAT NOT NULL DEFAULT '0',
  `em6_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em6_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em6_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em6_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em6_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em6_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `text7_0` LONGTEXT NOT NULL,
  `text7_1` LONGTEXT NOT NULL,
  `lang7` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `prob7` FLOAT NOT NULL DEFAULT '0',
  `em7_0` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em7_1` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em7_2` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em7_3` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em7_4` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `em7_5` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`npc_gossip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`npc_gossip` (
  `npc_guid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `textid` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  INDEX `guid_creature_idx` (`npc_guid` ASC),
  INDEX `text_id_idx` (`textid` ASC),
  CONSTRAINT `guid_creature`
    FOREIGN KEY (`npc_guid`)
    REFERENCES `alpha_world`.`spawns_creatures` (`spawn_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `text_id`
    FOREIGN KEY (`textid`)
    REFERENCES `alpha_world`.`npc_text` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`npc_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`npc_trainer` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `spellcost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `spellpointcost` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `reqskill` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `reqskillvalue` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `reqlevel` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  UNIQUE INDEX `entry_spell` (`entry` ASC, `spell` ASC),
  CONSTRAINT `trainer_entry`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`npc_vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`npc_vendor` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `incrtime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `itemflags` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `vendor_item_idx` (`item` ASC),
  CONSTRAINT `fk_npc_vendor_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_npc_vendor_2`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`pickpocketing_loot_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`pickpocketing_loot_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `condition_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `pick_item_idx` (`item` ASC),
  CONSTRAINT `fk_pickpocketing_loot_template_1`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pickpocketing_loot_template_2`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`player_classlevelstats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`player_classlevelstats` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `class` TINYINT(3) UNSIGNED NOT NULL,
  `level` TINYINT(3) UNSIGNED NOT NULL,
  `basehp` SMALLINT(5) UNSIGNED NOT NULL,
  `basemana` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`class`, `level`, `id`),
  INDEX `Id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 541
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`player_levelstats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`player_levelstats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `race` TINYINT(3) UNSIGNED NOT NULL,
  `class` TINYINT(3) UNSIGNED NOT NULL,
  `level` TINYINT(3) UNSIGNED NOT NULL,
  `str` TINYINT(3) UNSIGNED NOT NULL,
  `agi` TINYINT(3) UNSIGNED NOT NULL,
  `sta` TINYINT(3) UNSIGNED NOT NULL,
  `inte` TINYINT(3) UNSIGNED NOT NULL,
  `spi` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY (`race`, `class`, `level`, `id`),
  INDEX `Id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2425
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`playercreateinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`playercreateinfo` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `map` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `zone` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `position_x` FLOAT NOT NULL DEFAULT '0',
  `position_y` FLOAT NOT NULL DEFAULT '0',
  `position_z` FLOAT NOT NULL DEFAULT '0',
  `orientation` FLOAT NOT NULL DEFAULT '0',
  PRIMARY KEY (`race`, `class`, `id`),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`playercreateinfo_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`playercreateinfo_action` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `button` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `action` INT(11) UNSIGNED NOT NULL DEFAULT '0',
  `type` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`race`, `class`, `button`, `id`),
  INDEX `playercreateinfo_race_class_index` (`race` ASC, `class` ASC),
  INDEX `id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`playercreateinfo_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`playercreateinfo_item` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `itemid` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `amount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `playercreateinfo_race_class_index` (`race` ASC, `class` ASC),
  INDEX `Id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 301
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`playercreateinfo_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`playercreateinfo_skill` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `Skill` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `SkillMin` SMALLINT(5) NOT NULL DEFAULT '0',
  `SkillMax` SMALLINT(5) NOT NULL DEFAULT '0',
  `Note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`race`, `class`, `Skill`, `id`),
  INDEX `Id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2201
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`playercreateinfo_spell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`playercreateinfo_spell` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `race` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `class` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `Spell` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `Note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`race`, `class`, `Spell`, `id`),
  INDEX `Id` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1498
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`reference_loot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`reference_loot` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `lootcondition` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `condition_value1` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `condition_value2` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `ref_item_idx` (`item` ASC),
  CONSTRAINT `ref_item`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`reference_loot_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`reference_loot_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `condition_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `ref_loot_template_item_idx` (`item` ASC),
  CONSTRAINT `ref_loot_template_item`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`skinning_loot_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`skinning_loot_template` (
  `entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `item` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  `ChanceOrQuestChance` FLOAT NOT NULL DEFAULT '100',
  `groupid` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `mincountOrRef` MEDIUMINT(9) NOT NULL DEFAULT '1',
  `maxcount` TINYINT(3) UNSIGNED NOT NULL DEFAULT '1',
  `condition_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`entry`, `item`),
  INDEX `skinning_item_idx` (`item` ASC),
  CONSTRAINT `skinning_creature`
    FOREIGN KEY (`entry`)
    REFERENCES `alpha_world`.`creatures` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `skinning_item`
    FOREIGN KEY (`item`)
    REFERENCES `alpha_world`.`item_template` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`spawns_gameobjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`spawns_gameobjects` (
  `spawn_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Global Unique Identifier',
  `displayid` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `spawn_entry` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Gameobject Identifier',
  `spawn_map` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Map Identifier',
  `spawn_positionX` FLOAT NOT NULL DEFAULT '0',
  `spawn_positionY` FLOAT NOT NULL DEFAULT '0',
  `spawn_positionZ` FLOAT NOT NULL DEFAULT '0',
  `spawn_orientation` FLOAT NOT NULL DEFAULT '0',
  `spawn_rotation0` FLOAT NOT NULL DEFAULT '0',
  `spawn_rotation1` FLOAT NOT NULL DEFAULT '0',
  `spawn_rotation2` FLOAT NOT NULL DEFAULT '0',
  `spawn_rotation3` FLOAT NOT NULL DEFAULT '0',
  `spawn_spawntime` INT(11) NOT NULL DEFAULT '0',
  `spawn_animprogress` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `spawn_state` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`spawn_id`),
  INDEX `gobject_spawn_entry_idx` (`spawn_entry` ASC),
  CONSTRAINT `gobject_spawn_entry`
    FOREIGN KEY (`spawn_entry`)
    REFERENCES `alpha_world`.`gameobjects` (`entry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 99999
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `is_bug` INT(1) NOT NULL DEFAULT '0',
  `account_name` VARCHAR(250) NOT NULL DEFAULT '',
  `account_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `character_name` VARCHAR(12) NOT NULL DEFAULT '',
  `text_body` TEXT NOT NULL,
  `submit_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `account_id` (`account_id` ASC),
  CONSTRAINT `tickets_ibfk_1`
    FOREIGN KEY (`account_id`)
    REFERENCES `alpha_world`.`accounts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `alpha_world`.`worldports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alpha_world`.`worldports` (
  `entry` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `x` FLOAT NOT NULL DEFAULT '0',
  `y` FLOAT NOT NULL DEFAULT '0',
  `z` FLOAT NOT NULL DEFAULT '0',
  `map` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`entry`))
ENGINE = InnoDB
AUTO_INCREMENT = 371
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
